---
- name: install mariadb
  apt:
    name: mariadb-server
    update_cache: true
    state: present
  register: inst_mariadb

- name: initialize mariadb
  service:
    name: mariadb
    state: started
    enabled: true
  register: init_mariadb
